/**
 * Load anchored claims into Surveyor's context table.
 *
 * Usage:
 *   npx tsx scripts/harvest/load-claims.ts [--dry-run]
 */

import { readFileSync } from "fs";

// Load .env.local before any other imports that read env vars
for (const line of readFileSync(".env.local", "utf-8").split("\n")) {
  const idx = line.indexOf("=");
  if (idx < 1 || line.trimStart().startsWith("#")) continue;
  process.env[line.slice(0, idx).trim()] = line.slice(idx + 1).trim().replace(/\r$/, "");
}

import { loadClaims } from "./lib/store";
import type { HarvestedClaim } from "./lib/types";

const DRY_RUN = process.argv.includes("--dry-run");

// ---------------------------------------------------------------------------
// Group claims by entity
// ---------------------------------------------------------------------------

function groupByEntity(claims: HarvestedClaim[]): Map<string, HarvestedClaim[]> {
  const map = new Map<string, HarvestedClaim[]>();
  for (const c of claims) {
    if (!c.entityName) continue;
    const list = map.get(c.entityName) ?? [];
    list.push(c);
    map.set(c.entityName, list);
  }
  return map;
}

// ---------------------------------------------------------------------------
// Render markdown document for an entity's claims
// ---------------------------------------------------------------------------

function renderMarkdown(entityName: string, claims: HarvestedClaim[]): string {
  const date = new Date().toISOString().slice(0, 10);
  const uniqueSources = new Set(claims.map((c) => c.sourceRef));

  const sections: Record<string, HarvestedClaim[]> = {
    agrees: [],
    related: [],
    unanchored: [],
    contradicts: [],
  };

  for (const c of claims) {
    const bucket = sections[c.anchorStatus] ?? sections.unanchored;
    bucket.push(c);
  }

  const lines: string[] = [];
  lines.push(`# Harvested Knowledge: ${entityName}`);
  lines.push("");
  lines.push(`> Auto-generated by Context Harvester on ${date}.`);
  lines.push(`> ${claims.length} claims from ${uniqueSources.size} sources.`);

  const renderClaims = (list: HarvestedClaim[]) => {
    // Sort by field name for readability
    list.sort((a, b) => (a.fieldName ?? "").localeCompare(b.fieldName ?? ""));
    for (const c of list) {
      const field = c.fieldName ?? "general";
      lines.push(`- **${field}**: ${c.claimText}`);
      lines.push(`  _[${c.sourceRef}]_`);
    }
  };

  if (sections.agrees.length > 0) {
    lines.push("");
    lines.push("## Confirmed Mappings (agrees with SOT)");
    lines.push("");
    renderClaims(sections.agrees);
  }

  if (sections.related.length > 0) {
    lines.push("");
    lines.push("## Related Context (not in SOT)");
    lines.push("");
    renderClaims(sections.related);
  }

  if (sections.contradicts.length > 0) {
    lines.push("");
    lines.push("## Contradictions (disagrees with SOT)");
    lines.push("");
    renderClaims(sections.contradicts);
  }

  if (sections.unanchored.length > 0) {
    lines.push("");
    lines.push("## Unanchored (no SOT mapping found)");
    lines.push("");
    renderClaims(sections.unanchored);
  }

  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Compute source counts from claims
// ---------------------------------------------------------------------------

function sourceCounts(claims: HarvestedClaim[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const c of claims) {
    counts[c.source] = (counts[c.source] ?? 0) + 1;
  }
  return counts;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const claims = loadClaims("anchored-claims.json");
  if (claims.length === 0) {
    console.log("No anchored claims found. Run the anchor step first.");
    return;
  }

  const skipped = claims.filter((c) => !c.entityName);
  const grouped = groupByEntity(claims);

  console.log(`Loaded ${claims.length} claims (${skipped.length} skipped — null entity)`);
  console.log(`${grouped.size} entities to process`);
  if (DRY_RUN) console.log("DRY RUN — no DB writes\n");

  // Dynamic imports for DB access
  const { db } = await import("../../src/lib/db");
  const { context, entity } = await import("../../src/lib/db/schema");
  const { eq, and } = await import("drizzle-orm");
  const { estimateTokens } = await import("../../src/lib/llm/token-counter");

  // Resolve workspaceId from first entity in DB
  const firstEntity = await db.select().from(entity).limit(1);
  if (firstEntity.length === 0) {
    console.error("No entities found in DB. Cannot resolve workspaceId.");
    process.exit(1);
  }
  const workspaceId = firstEntity[0].workspaceId;
  console.log(`Workspace: ${workspaceId}\n`);

  let created = 0;
  let updated = 0;

  for (const [entityName, entityClaims] of grouped) {
    const markdown = renderMarkdown(entityName, entityClaims);
    const tokens = estimateTokens(markdown);
    const docName = `Harvested Knowledge > ${entityName}`;
    const uniqueMilestones = [...new Set(entityClaims.map((c) => c.milestone))];
    const avgConfidence =
      entityClaims.reduce((sum, c) => sum + c.confidence, 0) / entityClaims.length;

    // Resolve entity ID (target side)
    const matchedEntities = await db
      .select()
      .from(entity)
      .where(and(eq(entity.name, entityName), eq(entity.side, "target")));
    const entityId = matchedEntities.length > 0 ? matchedEntities[0].id : null;

    const tags = [
      "harvested",
      entityName.toLowerCase(),
      ...uniqueMilestones.map((m) => m.toLowerCase()),
    ];
    const meta = {
      harvest_date: new Date().toISOString().slice(0, 10),
      source_counts: sourceCounts(entityClaims),
      avg_confidence: Math.round(avgConfidence * 100) / 100,
    };

    console.log(
      `  ${entityName}: ${entityClaims.length} claims, ${tokens} tokens` +
        (entityId ? "" : " (no entity match)")
    );

    if (DRY_RUN) continue;

    // Check for existing doc
    const existing = await db
      .select()
      .from(context)
      .where(
        and(eq(context.name, docName), eq(context.importSource, "context_harvester"))
      );

    const now = new Date().toISOString();

    if (existing.length > 0) {
      await db
        .update(context)
        .set({
          content: markdown,
          tokenCount: tokens,
          metadata: meta,
          tags,
          updatedAt: now,
        })
        .where(eq(context.id, existing[0].id));
      updated++;
    } else {
      await db.insert(context).values({
        workspaceId,
        name: docName,
        category: "adhoc",
        subcategory: "extract",
        entityId,
        content: markdown,
        contentFormat: "markdown",
        tokenCount: tokens,
        tags,
        isActive: true,
        sortOrder: 0,
        importSource: "context_harvester",
        metadata: meta,
        createdAt: now,
        updatedAt: now,
      });
      created++;
    }
  }

  console.log(`\nDone. Created: ${created}, Updated: ${updated}, Entities: ${grouped.size}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
