import { db } from "@/lib/db";
import { entity, field, fieldMapping, batchRun, generation, question, workspace, mappingContext } from "@/lib/db/schema";
import { eq, and, inArray, sql } from "drizzle-orm";
import { startGeneration, executeGeneration, persistEntityPipeline } from "./runner";
import { classifyStructure, generateAssemblyYaml, scopeSourceSchema } from "./structure-classifier";
import { resolveProvider } from "./provider-resolver";
import { issueToQuestion, type ValidationIssue } from "./yaml-validator";
import { parseYamlOutput, type YamlParseResult } from "./output-parser";
import type { ParseResult, ParsedFieldMapping } from "@/types/generation";
import { extractCitations } from "./citation-parser";
import type { MappingStatus } from "@/lib/constants";
import { createBulkChatRun, executeBulkChatRun } from "./bulk-chat-runner";
import type { BigQueryConfig } from "@/types/workspace";
import {
  generateScaffold,
  loadCachedScaffold,
  persistScaffold,
  type EntityScaffoldData,
} from "./scaffolding";
import { buildDependencyGraph } from "./dependency-graph";
import { selectStrategy } from "./strategy-selector";
import { extractFKConstraints } from "./pattern-transfer";
import { FKConstraintStore } from "./fk-constraint-store";
import { verifyAndCorrectPipeline } from "./pipeline-verifier";

interface BatchRunInput {
  workspaceId: string;
  userId: string;
  preferredProvider?: "claude" | "openai";
  model?: string;
  includeStatuses?: MappingStatus[];
  outputFormat?: "json" | "yaml";
  enableStructureClassification?: boolean;
  entityIds?: string[];
}

interface EntityBatch {
  entityId: string;
  entityName: string;
  fieldCount: number;
}

/** Triage mapping status based on confidence level */
function triageStatus(fm: ParsedFieldMapping): MappingStatus {
  if (fm.status === "unmapped") return "unmapped";
  if (fm.confidence === "low") return "needs_discussion";
  return "unreviewed"; // medium and high
}

/**
 * Prepare a single entity for regeneration by retiring stale data:
 * 1. Mark old isLatest mappings as not-latest (so new ones take precedence)
 * 2. Dismiss open LLM/validator questions (human questions are preserved)
 *
 * Only affects the specific entity passed — does NOT cascade to children.
 * For assembly entities, call this separately for each component entity
 * inside generateAssemblyEntity.
 */
function prepareEntityForRegeneration(
  workspaceId: string,
  entityId: string,
  batchRunId: string,
): { mappingsRetired: number; questionsDismissed: number } {
  const now = new Date().toISOString();

  // Collect this entity + all descendant entities (assembly components, recursively)
  const allEntityIds = [entityId];
  const queue = [entityId];
  while (queue.length > 0) {
    const parentId = queue.shift()!;
    const children = db
      .select({ id: entity.id })
      .from(entity)
      .where(eq(entity.parentEntityId, parentId))
      .all();
    for (const child of children) {
      allEntityIds.push(child.id);
      queue.push(child.id);
    }
  }

  // Find all field IDs for this entity and its children
  const entityFields = db
    .select({ id: field.id })
    .from(field)
    .where(inArray(field.entityId, allEntityIds))
    .all();
  const fieldIds = entityFields.map((f) => f.id);

  let mappingsRetired = 0;
  if (fieldIds.length > 0) {
    // Mark old latest mappings as not-latest
    const result = db
      .update(fieldMapping)
      .set({
        isLatest: false,
        changeSummary: `Superseded by batch run ${batchRunId}`,
        updatedAt: now,
      })
      .where(
        and(
          eq(fieldMapping.workspaceId, workspaceId),
          eq(fieldMapping.isLatest, true),
          inArray(fieldMapping.targetFieldId, fieldIds)
        )
      )
      .run();
    mappingsRetired = result.changes;
  }

  // Dismiss stale open questions generated by LLM or validator
  // Human-asked questions (askedBy = 'user') are preserved
  // Includes child entity questions (assembly components)
  const dismissResult = db
    .update(question)
    .set({
      status: "dismissed",
      updatedAt: now,
    })
    .where(
      and(
        eq(question.workspaceId, workspaceId),
        inArray(question.entityId, allEntityIds),
        eq(question.status, "open"),
        sql`${question.askedBy} IN ('llm', 'validator')`
      )
    )
    .run();

  return {
    mappingsRetired,
    questionsDismissed: dismissResult.changes,
  };
}

/**
 * Create a batch run record and return it. Does NOT start processing.
 */
export function createBatchRun(input: BatchRunInput): {
  batchRunId: string;
  entities: EntityBatch[];
  totalFields: number;
} {
  const { workspaceId, userId } = input;
  const DEFAULT_INCLUDE: MappingStatus[] = ["unmapped", "unreviewed", "punted", "needs_discussion", "excluded"];
  const includeStatuses = new Set(input.includeStatuses ?? DEFAULT_INCLUDE);

  // Find all target entities
  const targetEntities = db
    .select()
    .from(entity)
    .where(and(eq(entity.workspaceId, workspaceId), eq(entity.side, "target")))
    .orderBy(entity.sortOrder)
    .all();

  if (targetEntities.length === 0) {
    throw new Error("No target entities found in workspace");
  }

  // Filter to specific entities if entityIds provided
  const filteredEntities = input.entityIds?.length
    ? targetEntities.filter((e) => input.entityIds!.includes(e.id))
    : targetEntities;

  if (filteredEntities.length === 0) {
    throw new Error("No matching target entities found for the selected IDs");
  }

  // Build targetFieldId → current status map
  const fieldStatusMap = new Map<string, MappingStatus>();
  const existing = db
    .select({ targetFieldId: fieldMapping.targetFieldId, status: fieldMapping.status })
    .from(fieldMapping)
    .where(
      and(
        eq(fieldMapping.workspaceId, workspaceId),
        eq(fieldMapping.isLatest, true)
      )
    )
    .all();
  for (const m of existing) fieldStatusMap.set(m.targetFieldId, m.status as MappingStatus);

  // Count eligible fields per entity
  const entities: EntityBatch[] = [];
  let totalFields = 0;

  for (const e of filteredEntities) {
    const fields = db
      .select()
      .from(field)
      .where(eq(field.entityId, e.id))
      .all();

    const eligible = fields.filter((f) => {
      const currentStatus = fieldStatusMap.get(f.id) ?? "unmapped";
      return includeStatuses.has(currentStatus);
    });

    if (eligible.length > 0) {
      entities.push({
        entityId: e.id,
        entityName: e.displayName || e.name,
        fieldCount: eligible.length,
      });
      totalFields += eligible.length;
    }
  }

  if (entities.length === 0) {
    throw new Error("No eligible fields found for the selected statuses");
  }

  // Create batch run record
  const batchRunId = crypto.randomUUID();
  const now = new Date().toISOString();

  db.insert(batchRun)
    .values({
      id: batchRunId,
      workspaceId,
      status: "pending",
      totalEntities: entities.length,
      completedEntities: 0,
      failedEntities: 0,
      totalFields,
      completedFields: 0,
      config: {
        provider: input.preferredProvider,
        model: input.model,
        includeStatuses: Array.from(includeStatuses),
      },
      createdBy: userId,
      createdAt: now,
      updatedAt: now,
    }).run();

  return { batchRunId, entities, totalFields };
}

/**
 * Generate mappings for a single flat entity and save results.
 * Returns the number of fields completed, or throws on failure.
 */
async function generateFlatEntity(
  batch: EntityBatch,
  workspaceId: string,
  userId: string,
  batchRunId: string,
  outputFormat: "json" | "yaml",
  preferredProvider?: "claude" | "openai",
  model?: string,
  bqConfig?: BigQueryConfig,
  fkConstraints?: import("./fk-constraint-store").FKConstraint[],
): Promise<{ fieldsCompleted: number }> {
  const { prepared } = startGeneration({
    workspaceId,
    userId,
    entityId: batch.entityId,
    generationType: "field_mapping",
    preferredProvider,
    model,
    outputFormat,
    bqConfig,
    fkConstraints,
  });

  // Link generation to batch run
  db.update(generation)
    .set({ batchRunId })
    .where(eq(generation.id, prepared.generationId))
    .run();

  // Execute LLM call (includes validation + correction loop for YAML)
  await executeGeneration(prepared);

  // Read the completed generation
  const gen = db
    .select()
    .from(generation)
    .where(eq(generation.id, prepared.generationId))
    .get();

  if (!gen || gen.status !== "completed" || !gen.outputParsed) {
    throw new Error(`Generation ${prepared.generationId} failed or produced no output`);
  }

  const parsed = gen.outputParsed as unknown as ParseResult;

  // Save mappings and create questions
  const { questionsCreated, mappingLookup, fieldsWithExplicitQuestion, resolvedFieldIds } = saveMappingsAndQuestions(
    parsed,
    batch,
    workspaceId,
    userId,
    prepared.generationId,
    batchRunId,
  );

  // Populate mappingContext junction table — link each new mapping to context
  // docs that were actually cited in its reasoning/notes. Falls back to all
  // available context if no citations were found (older models or uncited output).
  const promptSnap = gen.promptSnapshot as Record<string, unknown> | null;
  const contextUsed = (promptSnap?.contextUsed ?? []) as { id: string; name: string; tokens: number }[];
  if (contextUsed.length > 0) {
    const contextIdSet = new Set(contextUsed.map((c) => c.id));

    // Build per-mapping citation index from parsed output
    const citationsByField = new Map<string, Set<string>>();
    for (const fm of parsed.fieldMappings) {
      const cited = extractCitations(fm.reasoning, fm.notes, fm.reviewComment);
      // Only keep citations that match actual context IDs from the prompt
      const validCited = new Set([...cited].filter((id) => contextIdSet.has(id)));
      if (validCited.size > 0) {
        citationsByField.set(fm.targetFieldName.toLowerCase(), validCited);
      }
    }

    const rows: { fieldMappingId: string; contextId: string; contextType: string }[] = [];
    for (const [fieldName, info] of mappingLookup) {
      const cited = citationsByField.get(fieldName);
      if (cited && cited.size > 0) {
        // Citation-based: only link docs the LLM actually referenced
        for (const ctxId of cited) {
          rows.push({
            fieldMappingId: info.mappingId,
            contextId: ctxId,
            contextType: "context_reference",
          });
        }
      } else {
        // Fallback: no citations found, link all context (backwards compat)
        for (const ctx of contextUsed) {
          rows.push({
            fieldMappingId: info.mappingId,
            contextId: ctx.id,
            contextType: "context_reference",
          });
        }
      }
    }
    // Batch insert in chunks of 500 (SQLite variable limit)
    for (let i = 0; i < rows.length; i += 500) {
      db.insert(mappingContext).values(rows.slice(i, i + 500)).run();
    }
  }

  // Create questions from validation issues (YAML path)
  if (outputFormat === "yaml") {
    const validationQuestions = createValidationQuestions(
      gen.validationIssues as unknown as ValidationIssue[] | null,
      batch,
      workspaceId,
      userId,
      mappingLookup,
      fieldsWithExplicitQuestion,
      resolvedFieldIds,
    );

    if (validationQuestions > 0) {
      console.log(`[batch] Created ${validationQuestions} validation questions for "${batch.entityName}"`);
    }

    // Persist entity pipeline
    try {
      const yamlResult = gen.outputParsed as unknown as YamlParseResult;
      if (yamlResult.yamlParsed) {
        persistEntityPipeline({
          workspaceId,
          entityId: batch.entityId,
          yamlResult,
          generationId: prepared.generationId,
          batchRunId,
        });

        // Post-generation SQL verification with auto-correction
        if (bqConfig) {
          try {
            const verifyResult = await verifyAndCorrectPipeline({
              workspaceId,
              entityId: batch.entityId,
              entityName: batch.entityName,
              bqConfig: { projectId: bqConfig.projectId, sourceDataset: bqConfig.sourceDataset },
              generationId: prepared.generationId,
              batchRunId,
              userId,
              preferredProvider,
              model,
            });
            if (verifyResult.status !== "passed" && verifyResult.status !== "skipped") {
              console.log(
                `[batch] SQL verification for "${batch.entityName}": ${verifyResult.status}`,
                verifyResult.correctedColumns || verifyResult.flaggedColumns || "",
              );
            }
          } catch (verifyErr) {
            console.warn(`[batch] SQL verification error for "${batch.entityName}":`, verifyErr);
          }
        }
      }
    } catch (pipelineErr) {
      console.warn(`[batch] Failed to persist pipeline for "${batch.entityName}":`, pipelineErr);
    }
  }

  if (questionsCreated > 0) {
    console.log(`[batch] Created ${questionsCreated} questions for "${batch.entityName}"`);
  }

  return { fieldsCompleted: parsed.fieldMappings.length };
}

/**
 * Generate mappings for an assembly entity using two-pass component generation.
 * 1. Generate each component separately with scoped source schema
 * 2. Generate assembly YAML mechanically (no LLM)
 */
async function generateAssemblyEntity(
  batch: EntityBatch,
  components: { name: string; description: string; sourceFieldPattern: string | null; filter: string | null }[],
  sourceSchema: { entityName: string; fields: { name: string; dataType: string | null }[] }[],
  workspaceId: string,
  userId: string,
  batchRunId: string,
  preferredProvider?: "claude" | "openai",
  model?: string,
  bqConfig?: BigQueryConfig,
  fkConstraints?: import("./fk-constraint-store").FKConstraint[],
): Promise<{ fieldsCompleted: number }> {
  let totalFields = 0;

  // Load target field names for assembly generation
  const targetFields = db
    .select()
    .from(field)
    .where(eq(field.entityId, batch.entityId))
    .orderBy(field.sortOrder)
    .all();
  const targetColumnNames = targetFields.map((f) => f.name);

  // Generate each component
  for (const comp of components) {
    try {
      // Find or create a component entity record
      const compEntityName = comp.name;
      let compEntity = db
        .select()
        .from(entity)
        .where(and(eq(entity.workspaceId, workspaceId), eq(entity.name, compEntityName)))
        .get();

      if (!compEntity) {
        // Find the parent entity to get its schemaAssetId
        const parentEntity = db
          .select()
          .from(entity)
          .where(eq(entity.id, batch.entityId))
          .get();

        if (!parentEntity) {
          console.warn(`[batch] Parent entity ${batch.entityId} not found, skipping component "${comp.name}"`);
          continue;
        }

        // Create component entity
        const compEntityId = crypto.randomUUID();
        const nowTs = new Date().toISOString();
        db.insert(entity)
          .values({
            id: compEntityId,
            workspaceId,
            schemaAssetId: parentEntity.schemaAssetId,
            name: compEntityName,
            displayName: comp.description,
            side: "target",
            description: `Component of ${batch.entityName}: ${comp.description}`,
            parentEntityId: batch.entityId,
            createdAt: nowTs,
            updatedAt: nowTs,
          })
          .run();

        // Copy target fields to component entity
        for (const tf of targetFields) {
          db.insert(field)
            .values({
              entityId: compEntityId,
              name: tf.name,
              dataType: tf.dataType,
              isRequired: tf.isRequired,
              isKey: tf.isKey,
              description: tf.description,
              enumValues: tf.enumValues,
              sampleValues: tf.sampleValues,
              sortOrder: tf.sortOrder,
            })
            .run();
        }

        compEntity = db.select().from(entity).where(eq(entity.id, compEntityId)).get()!;
      }

      // Retire stale mappings/questions for this component entity
      const compCleanup = prepareEntityForRegeneration(workspaceId, compEntity.id, batchRunId);
      if (compCleanup.mappingsRetired > 0 || compCleanup.questionsDismissed > 0) {
        console.log(
          `[batch] Cleanup component "${comp.name}": retired ${compCleanup.mappingsRetired} mappings, dismissed ${compCleanup.questionsDismissed} stale questions`,
        );
      }

      // Scope source schema for this component
      const scopedSchema = scopeSourceSchema(sourceSchema, comp, components);

      console.log(
        `[batch] Generating component "${comp.name}" with ${scopedSchema.reduce((n, s) => n + s.fields.length, 0)} scoped source fields`,
      );

      // Generate the component using existing infrastructure
      const result = await generateFlatEntity(
        { entityId: compEntity.id, entityName: compEntityName, fieldCount: targetFields.length },
        workspaceId,
        userId,
        batchRunId,
        "yaml",
        preferredProvider,
        model,
        bqConfig,
        fkConstraints,
      );
      totalFields += result.fieldsCompleted;
    } catch (compErr) {
      console.warn(`[batch] Component "${comp.name}" generation failed:`, compErr);
    }
  }

  // Generate assembly YAML mechanically
  try {
    const assemblyYamlStr = generateAssemblyYaml(
      batch.entityName,
      components.map((c) => ({
        name: c.name,
        alias: c.name.split("_").pop() || c.name,
      })),
      targetColumnNames,
    );

    // Parse the assembly YAML and persist it
    const resolutionCtx = {
      targetFields: targetFields.map((f) => ({ id: f.id, name: f.name, entityId: f.entityId })),
      sourceEntities: components.map((c) => ({ id: c.name, name: c.name })),
      sourceFields: [],
      requestedFieldNames: targetColumnNames,
    };
    const assemblyParsed = parseYamlOutput(assemblyYamlStr, resolutionCtx);

    if (assemblyParsed.yamlParsed) {
      persistEntityPipeline({
        workspaceId,
        entityId: batch.entityId,
        yamlResult: assemblyParsed,
        generationId: batchRunId, // No individual generation for assembly
        batchRunId,
      });
      console.log(`[batch] Persisted assembly pipeline for "${batch.entityName}"`);

      // Post-generation SQL verification for assembly pipeline
      if (bqConfig) {
        try {
          const verifyResult = await verifyAndCorrectPipeline({
            workspaceId,
            entityId: batch.entityId,
            entityName: batch.entityName,
            bqConfig: { projectId: bqConfig.projectId, sourceDataset: bqConfig.sourceDataset },
            generationId: batchRunId,
            batchRunId,
            userId,
            preferredProvider,
            model,
          });
          if (verifyResult.status !== "passed" && verifyResult.status !== "skipped") {
            console.log(
              `[batch] Assembly SQL verification for "${batch.entityName}": ${verifyResult.status}`,
              verifyResult.correctedColumns || verifyResult.flaggedColumns || "",
            );
          }
        } catch (verifyErr) {
          console.warn(`[batch] Assembly SQL verification error for "${batch.entityName}":`, verifyErr);
        }
      }
    }
  } catch (assemblyErr) {
    console.warn(`[batch] Assembly pipeline generation failed for "${batch.entityName}":`, assemblyErr);
  }

  return { fieldsCompleted: totalFields };
}

/**
 * Get entity IDs of sibling components (same parentEntityId).
 * Returns empty array if entity has no parent.
 */
function getSiblingEntityIds(workspaceId: string, entityId: string): string[] {
  const e = db
    .select({ parentEntityId: entity.parentEntityId })
    .from(entity)
    .where(eq(entity.id, entityId))
    .get();

  if (!e?.parentEntityId) return [];

  return db
    .select({ id: entity.id })
    .from(entity)
    .where(
      and(
        eq(entity.workspaceId, workspaceId),
        eq(entity.parentEntityId, e.parentEntityId),
      )
    )
    .all()
    .filter((sib) => sib.id !== entityId)
    .map((sib) => sib.id);
}

/**
 * Check if a question is about a source field whose enum values are already
 * documented. These are "low ambiguity" questions — the LLM had the answer
 * in its context but asked anyway.
 *
 * Returns the matched field name if the question is enum-answerable, null otherwise.
 */
function isEnumAnswerable(
  questionText: string,
  workspaceId: string,
): string | null {
  // Build set of source field names with documented enum values
  const sourceFieldsWithEnums = db
    .select({ fieldName: field.name })
    .from(field)
    .innerJoin(entity, eq(field.entityId, entity.id))
    .where(
      and(
        eq(entity.workspaceId, workspaceId),
        eq(entity.side, "source"),
        sql`${field.enumValues} IS NOT NULL AND ${field.enumValues} != '[]' AND ${field.enumValues} != 'null'`,
      )
    )
    .all();

  const qLower = questionText.toLowerCase();

  // Value-inquiry keywords — question is asking about the values/codes of a field
  const valuePatterns = [
    "validate", "value", "consistent", "correct", "filter",
    "indicator", "which code", "what code", "what value",
    "use a different", "might use", "should we",
  ];
  const hasValueInquiry = valuePatterns.some((p) => qLower.includes(p));
  if (!hasValueInquiry) return null;

  // Check if the question mentions any enum-documented source field
  for (const { fieldName } of sourceFieldsWithEnums) {
    if (qLower.includes(fieldName.toLowerCase())) {
      return fieldName;
    }
  }

  return null;
}

/**
 * Check if a question is about a deprecated target field. The LLM should
 * auto-unmap these, but if it asks anyway we suppress the question.
 */
function isDeprecatedFieldQuestion(questionText: string): boolean {
  const qLower = questionText.toLowerCase();
  return qLower.includes("deprecated") && (
    qLower.includes("skip") ||
    qLower.includes("instead") ||
    qLower.includes("should we map") ||
    qLower.includes("should we still")
  );
}

/**
 * Save field mappings and LLM-generated questions from a parsed generation result.
 * Returns the lookup map and fields that already have questions.
 */
function saveMappingsAndQuestions(
  parsed: ParseResult,
  batch: EntityBatch,
  workspaceId: string,
  userId: string,
  generationId: string,
  batchRunId: string,
): {
  questionsCreated: number;
  mappingLookup: Map<string, { mappingId: string; targetFieldId: string; confidence: string | null; reviewComment: string | null; uncertaintyType: string | null }>;
  fieldsWithExplicitQuestion: Set<string>;
  resolvedFieldIds: Set<string>;
} {
  const mappingLookup = new Map<string, {
    mappingId: string;
    targetFieldId: string;
    confidence: string | null;
    reviewComment: string | null;
    uncertaintyType: string | null;
  }>();

  // Build set of field IDs that already have resolved OR dismissed answers — skip question
  // creation for these. Dismissed questions indicate a human already decided the question
  // is not worth asking; resolved questions have an actual answer. Both should prevent
  // the LLM from re-asking the same question on subsequent batch runs.
  // Also check sibling component entities (same parentEntityId) since assembly components
  // share the same field names and a resolution on one sibling applies to all.
  const siblingEntityIds = getSiblingEntityIds(workspaceId, batch.entityId);
  const entityIdsToCheck = [batch.entityId, ...siblingEntityIds];

  const resolvedQuestions = db
    .select({ fieldId: question.fieldId })
    .from(question)
    .where(
      and(
        inArray(question.entityId, entityIdsToCheck),
        inArray(question.status, ["resolved", "dismissed"]),
        sql`${question.fieldId} IS NOT NULL`,
      )
    )
    .all();

  // For sibling fields, map by field name since field IDs differ across components
  const resolvedFieldIds = new Set(resolvedQuestions.map((rq) => rq.fieldId!));
  if (siblingEntityIds.length > 0) {
    const resolvedFieldNames = new Set<string>();
    for (const rq of resolvedQuestions) {
      const f = db.select({ name: field.name }).from(field).where(eq(field.id, rq.fieldId!)).get();
      if (f) resolvedFieldNames.add(f.name.toLowerCase());
    }
    // Add this entity's field IDs that match resolved sibling field names
    if (resolvedFieldNames.size > 0) {
      const entityFields = db.select({ id: field.id, name: field.name }).from(field)
        .where(eq(field.entityId, batch.entityId)).all();
      for (const ef of entityFields) {
        if (resolvedFieldNames.has(ef.name.toLowerCase())) {
          resolvedFieldIds.add(ef.id);
        }
      }
    }
  }

  // Auto-save field mappings with explicit UUIDs and confidence-based triage
  for (const fm of parsed.fieldMappings) {
    if (!fm.targetFieldId) continue;

    const mappingId = crypto.randomUUID();
    const status = triageStatus(fm);

    db.insert(fieldMapping)
      .values({
        id: mappingId,
        workspaceId,
        targetFieldId: fm.targetFieldId,
        status,
        mappingType: fm.mappingType,
        sourceEntityId: fm.sourceEntityId,
        sourceFieldId: fm.sourceFieldId,
        transform: fm.transform,
        defaultValue: fm.defaultValue,
        enumMapping: fm.enumMapping,
        reasoning: fm.reasoning,
        confidence: fm.confidence,
        notes: fm.reviewComment || fm.notes,
        createdBy: "llm",
        assigneeId: userId,
        generationId,
        batchRunId,
        version: 1,
        isLatest: true,
      }).run();

    mappingLookup.set(
      fm.targetFieldName.toLowerCase(),
      {
        mappingId,
        targetFieldId: fm.targetFieldId,
        confidence: fm.confidence,
        reviewComment: fm.reviewComment,
        uncertaintyType: fm.uncertaintyType,
      },
    );
  }

  // Auto-create question records
  let questionsCreated = 0;
  const fieldsWithExplicitQuestion = new Set<string>();

  // 1. From parsed.questions (LLM-generated)
  if (parsed.questions?.length) {
    for (const pq of parsed.questions) {
      const lookup = pq.targetFieldName
        ? mappingLookup.get(pq.targetFieldName.toLowerCase())
        : null;

      if (pq.targetFieldName) {
        fieldsWithExplicitQuestion.add(pq.targetFieldName.toLowerCase());
      }

      // Skip if this field already has a resolved answer
      const resolvedFieldId = pq.targetFieldId ?? lookup?.targetFieldId;
      if (resolvedFieldId && resolvedFieldIds.has(resolvedFieldId)) continue;

      // Skip "low ambiguity" questions — answer is in the enum context
      const enumField = isEnumAnswerable(pq.questionText, workspaceId);
      if (enumField) {
        console.log(`[batch] Suppressed enum-answerable question about "${enumField}" for "${batch.entityName}": ${pq.questionText.slice(0, 80)}...`);
        continue;
      }

      // Skip questions about deprecated fields — LLM should auto-unmap these
      if (isDeprecatedFieldQuestion(pq.questionText)) {
        console.log(`[batch] Suppressed deprecated-field question for "${batch.entityName}": ${pq.questionText.slice(0, 80)}...`);
        continue;
      }

      try {
        db.insert(question).values({
          workspaceId,
          entityId: batch.entityId,
          fieldId: pq.targetFieldId ?? lookup?.targetFieldId ?? null,
          question: pq.questionText,
          status: "open",
          askedBy: "llm",
          priority: pq.priority,
          targetForTeam: "SM",
          fieldMappingId: lookup?.mappingId ?? null,
          createdByUserId: userId,
        }).run();
        questionsCreated++;
      } catch (qErr) {
        console.warn(`[batch] Failed to create question for "${pq.targetFieldName}":`, qErr);
      }
    }
  }

  // 2. Gap-fill: auto-create questions for medium/low confidence mappings
  //    that don't already have an explicit question
  for (const [fieldName, info] of mappingLookup) {
    if (fieldsWithExplicitQuestion.has(fieldName)) continue;
    if (resolvedFieldIds.has(info.targetFieldId)) continue;

    const shouldCreate =
      (info.confidence === "low") ||
      (info.confidence === "medium" && info.reviewComment);

    if (shouldCreate && info.reviewComment) {
      // Skip "low ambiguity" questions — answer is in the enum context
      const enumField = isEnumAnswerable(info.reviewComment, workspaceId);
      if (enumField) {
        console.log(`[batch] Suppressed enum-answerable gap-fill question about "${enumField}" for "${batch.entityName}"`);
        continue;
      }

      const priority = info.confidence === "low" ? "high" : "normal";
      try {
        db.insert(question).values({
          workspaceId,
          entityId: batch.entityId,
          fieldId: info.targetFieldId,
          question: info.reviewComment,
          status: "open",
          askedBy: "llm",
          priority,
          targetForTeam: "SM",
          fieldMappingId: info.mappingId,
          createdByUserId: userId,
        }).run();
        questionsCreated++;
      } catch {
        // Non-critical — continue
      }
    }
  }

  return { questionsCreated, mappingLookup, fieldsWithExplicitQuestion, resolvedFieldIds };
}

/**
 * Create question records from unresolved validation issues.
 */
function createValidationQuestions(
  validationIssues: ValidationIssue[] | null,
  batch: EntityBatch,
  workspaceId: string,
  userId: string,
  mappingLookup: Map<string, { mappingId: string; targetFieldId: string; confidence: string | null; reviewComment: string | null; uncertaintyType: string | null }>,
  fieldsWithExplicitQuestion: Set<string>,
  resolvedFieldIds: Set<string>,
): number {
  if (!validationIssues?.length) return 0;

  let questionsCreated = 0;
  const unresolvedErrors = validationIssues.filter((i) => i.severity === "error");

  for (const issue of unresolvedErrors) {
    const fieldKey = issue.field.toLowerCase();
    if (fieldsWithExplicitQuestion.has(fieldKey)) continue;
    fieldsWithExplicitQuestion.add(fieldKey);

    const lookup = mappingLookup.get(fieldKey);
    if (lookup?.targetFieldId && resolvedFieldIds.has(lookup.targetFieldId)) continue;

    const questionText = issueToQuestion(issue);

    try {
      db.insert(question).values({
        workspaceId,
        entityId: batch.entityId,
        fieldId: lookup?.targetFieldId ?? null,
        question: questionText,
        status: "open",
        askedBy: "validator",
        priority: "high",
        targetForTeam: "SM",
        fieldMappingId: lookup?.mappingId ?? null,
        createdByUserId: userId,
      }).run();
      questionsCreated++;
    } catch {
      // Non-critical — continue
    }
  }

  return questionsCreated;
}

/**
 * Execute a batch run: process entities sequentially, generate mappings,
 * and auto-save results as fieldMapping records.
 * Designed to be called fire-and-forget.
 */
export async function executeBatchRun(
  batchRunId: string,
  entities: EntityBatch[],
  input: BatchRunInput
): Promise<void> {
  const { workspaceId, userId, preferredProvider, model } = input;
  const now = () => new Date().toISOString();

  let completedEntities = 0;
  let failedEntities = 0;
  let completedFields = 0;

  // Load workspace BQ config for tool-enabled generation
  const ws = db
    .select({ settings: workspace.settings })
    .from(workspace)
    .where(eq(workspace.id, workspaceId))
    .get();
  const wsSettings = ws?.settings as Record<string, unknown> | null;
  const bqConfig = wsSettings?.bigquery as BigQueryConfig | undefined;

  try {
    // Mark as running
    db.update(batchRun)
      .set({ status: "running", startedAt: now(), updatedAt: now() })
      .where(eq(batchRun.id, batchRunId))
      .run();

    const outputFormat = input.outputFormat ?? "json";
    const enableClassification = input.enableStructureClassification ?? (outputFormat === "yaml");

    // ── Scaffolding pre-pass: analyze all entities before generation ──
    const scaffoldMap = new Map<string, EntityScaffoldData>();
    for (const batch of entities) {
      try {
        // Check for cached scaffold
        const cached = loadCachedScaffold(workspaceId, batch.entityId);
        if (cached) {
          scaffoldMap.set(batch.entityId, cached);
          continue;
        }

        // Generate fresh scaffold
        const scaffold = generateScaffold(workspaceId, batch.entityId);
        persistScaffold(workspaceId, batch.entityId, scaffold, { batchRunId });
        scaffoldMap.set(batch.entityId, scaffold);
        console.log(
          `[batch] Scaffolded "${batch.entityName}": ${scaffold.topology}, ` +
          `primary=[${scaffold.primarySources.join(", ")}]`,
        );
      } catch (scaffoldErr) {
        console.warn(`[batch] Scaffolding failed for "${batch.entityName}", will use fallback:`, scaffoldErr);
      }
    }

    // ── Dependency graph: reorder entities for FK consistency ──
    const fkStore = new FKConstraintStore();
    let orderedEntities = entities;

    try {
      const depGraph = buildDependencyGraph(workspaceId);
      if (depGraph.cycles.length > 0) {
        console.warn(`[batch] Dependency cycles detected:`, depGraph.cycles);
      }

      // Reorder entities to match topological sort (keep only entities in this batch)
      const batchEntityIds = new Set(entities.map((e) => e.entityId));
      const sortedIds = depGraph.sorted.filter((id) => batchEntityIds.has(id));
      const entityMap = new Map(entities.map((e) => [e.entityId, e]));

      // Build ordered list: sorted entities first, then any not in the graph
      const ordered: EntityBatch[] = [];
      const seen = new Set<string>();
      for (const id of sortedIds) {
        const batch = entityMap.get(id);
        if (batch) {
          ordered.push(batch);
          seen.add(id);
        }
      }
      // Add any entities not in the dependency graph
      for (const batch of entities) {
        if (!seen.has(batch.entityId)) ordered.push(batch);
      }

      orderedEntities = ordered;
      console.log(
        `[batch] Entity order (topological, ${depGraph.source}): ${orderedEntities.map((e) => e.entityName).join(" → ")}`,
      );
    } catch (depErr) {
      console.warn(`[batch] Dependency graph failed, using original order:`, depErr);
    }

    for (const batch of orderedEntities) {
      // Check for cancellation before each entity
      const currentRun = db.select({ status: batchRun.status }).from(batchRun).where(eq(batchRun.id, batchRunId)).get();
      if (currentRun?.status === "cancelled") {
        console.log(`[batch] Run ${batchRunId} cancelled, stopping after ${completedEntities} entities`);
        break;
      }

      try {
        // Report which entity is currently being processed
        try {
          db.update(batchRun)
            .set({ currentEntityName: batch.entityName, updatedAt: now() })
            .where(eq(batchRun.id, batchRunId))
            .run();
        } catch {
          // Non-critical — continue processing
        }

        // Retire stale mappings and dismiss LLM-generated questions
        const cleanup = prepareEntityForRegeneration(workspaceId, batch.entityId, batchRunId);
        if (cleanup.mappingsRetired > 0 || cleanup.questionsDismissed > 0) {
          console.log(
            `[batch] Cleanup "${batch.entityName}": retired ${cleanup.mappingsRetired} mappings, dismissed ${cleanup.questionsDismissed} stale questions`,
          );
        }

        // Structure classification + two-pass assembly flow
        // Use scaffold topology if available, fall back to LLM classification
        const scaffold = scaffoldMap.get(batch.entityId);
        if (enableClassification && outputFormat === "yaml") {
          try {
            const useAssembly = scaffold?.topology === "assembly";
            let classification: Awaited<ReturnType<typeof classifyStructure>> | null = null;

            if (!useAssembly) {
              // No scaffold assembly signal — try LLM classification as before
              const { provider } = resolveProvider(userId, preferredProvider);
              const sourceEntities = db
                .select()
                .from(entity)
                .where(and(eq(entity.workspaceId, workspaceId), eq(entity.side, "source")))
                .all();

              const sourceFields = db
                .select()
                .from(field)
                .all()
                .filter((f) => sourceEntities.some((e) => e.id === f.entityId));

              const sourceSchema = sourceEntities.map((se) => ({
                entityName: se.name,
                fields: sourceFields
                  .filter((sf) => sf.entityId === se.id)
                  .map((sf) => ({ name: sf.name, dataType: sf.dataType })),
              }));

              classification = await classifyStructure(
                batch.entityName,
                null,
                batch.fieldCount,
                sourceSchema,
                provider,
                model,
              );
            }

            if ((useAssembly || classification?.type === "assembly") && (scaffold?.assemblyComponents?.length || classification?.components?.length)) {
              const components = classification?.components ?? [];
              const sourceEntities = db
                .select()
                .from(entity)
                .where(and(eq(entity.workspaceId, workspaceId), eq(entity.side, "source")))
                .all();

              const sourceFields = db
                .select()
                .from(field)
                .all()
                .filter((f) => sourceEntities.some((e) => e.id === f.entityId));

              const sourceSchema = sourceEntities.map((se) => ({
                entityName: se.name,
                fields: sourceFields
                  .filter((sf) => sf.entityId === se.id)
                  .map((sf) => ({ name: sf.name, dataType: sf.dataType })),
              }));

              console.log(
                `[batch] Entity "${batch.entityName}" classified as assembly with components:`,
                components.map((c) => c.name),
              );

              // Two-pass assembly generation
              const accumulatedConstraints = fkStore.getAllConstraints();
              const result = await generateAssemblyEntity(
                batch,
                components,
                sourceSchema,
                workspaceId,
                userId,
                batchRunId,
                preferredProvider,
                model,
                bqConfig,
                accumulatedConstraints.length > 0 ? accumulatedConstraints : undefined,
              );
              completedFields += result.fieldsCompleted;
              completedEntities++;

              // Extract FK constraints from completed assembly entity
              try {
                const fkConstraints = extractFKConstraints(workspaceId, batch.entityId);
                if (fkConstraints.length > 0) {
                  fkStore.addConstraints(batch.entityName, fkConstraints.map((c) => ({
                    entityName: c.entityName,
                    idField: c.idField,
                    hashColumns: c.hashColumns,
                    transform: c.transform,
                  })));
                }
              } catch {
                // Non-critical
              }

              continue; // Skip flat generation below
            }
          } catch (classifyErr) {
            console.warn(
              `[batch] Structure classification failed for "${batch.entityName}", proceeding with flat generation:`,
              classifyErr,
            );
          }
        }

        // Flat entity generation (default path)
        const accumulatedFKConstraints = fkStore.getAllConstraints();
        const result = await generateFlatEntity(
          batch,
          workspaceId,
          userId,
          batchRunId,
          outputFormat,
          preferredProvider,
          model,
          bqConfig,
          accumulatedFKConstraints.length > 0 ? accumulatedFKConstraints : undefined,
        );
        completedFields += result.fieldsCompleted;
        completedEntities++;

        // Extract FK constraints from completed entity for downstream use
        try {
          const fkConstraints = extractFKConstraints(workspaceId, batch.entityId);
          if (fkConstraints.length > 0) {
            fkStore.addConstraints(batch.entityName, fkConstraints.map((c) => ({
              entityName: c.entityName,
              idField: c.idField,
              hashColumns: c.hashColumns,
              transform: c.transform,
            })));
          }
        } catch {
          // Non-critical — FK extraction failure doesn't block batch
        }
      } catch {
        failedEntities++;
      }

      // Update progress after each entity
      try {
        db.update(batchRun)
          .set({
            completedEntities,
            failedEntities,
            completedFields,
            updatedAt: now(),
          })
          .where(eq(batchRun.id, batchRunId))
          .run();
      } catch {
        // Progress update failed, continue processing
      }
    }

    // Mark as completed (preserve "cancelled" status if set)
    const finalCheck = db.select({ status: batchRun.status }).from(batchRun).where(eq(batchRun.id, batchRunId)).get();
    const finalStatus = finalCheck?.status === "cancelled"
      ? "cancelled"
      : failedEntities === entities.length ? "failed" : "completed";

    db.update(batchRun)
      .set({
        status: finalStatus,
        completedEntities,
        failedEntities,
        completedFields,
        currentEntityName: null,
        completedAt: now(),
        updatedAt: now(),
      })
      .where(eq(batchRun.id, batchRunId))
      .run();

    // Chat enrichment pass disabled — using Opus for batch which handles long context well.
    // Re-enable if per-field RAG tool access is needed.
    if (false && finalStatus === "completed") {
      try {
        const { batchRunId: chatRunId, entities: chatEntities } = createBulkChatRun({
          workspaceId: input.workspaceId,
          userId: input.userId,
          entityIds: input.entityIds,
          includeStatuses: ["unreviewed"],
        });
        executeBulkChatRun(chatRunId, chatEntities, {
          workspaceId: input.workspaceId,
          userId: input.userId,
          entityIds: input.entityIds,
          includeStatuses: ["unreviewed"],
        }).catch((err) => {
          console.error("[batch-runner] Chat enrichment pass failed:", err);
        });
      } catch (err) {
        // Non-critical — batch run already succeeded
        console.warn("[batch-runner] Could not start chat enrichment pass:", err);
      }
    }
  } catch (error) {
    console.error("[batch-runner] Fatal error in executeBatchRun:", error);
    // Ensure batch run is always marked as failed on unexpected errors
    try {
      db.update(batchRun)
        .set({
          status: "failed",
          completedEntities,
          failedEntities,
          completedFields,
          currentEntityName: null,
          completedAt: now(),
          updatedAt: now(),
        })
        .where(eq(batchRun.id, batchRunId))
        .run();
    } catch {
      // Last resort: can't even update the DB
      console.error("Failed to mark batch run as failed:", batchRunId, error);
    }
  }
}
